Repository MarcelCoding/bszet-mind, pull requests merged in 2023-01, with the labels that each got.

#8 Added notification images
  .gitignore
  Cargo.lock
  Cargo.toml
  Dockerfile
  bszet-davinci/Cargo.toml
  bszet-davinci/src/change.rs
  bszet-davinci/src/extractor/html_table.rs
  bszet-davinci/src/extractor/mod.rs
  bszet-davinci/src/extractor/parser.rs
  bszet-davinci/src/html/mod.rs
  bszet-davinci/src/lib.rs
  bszet-davinci/src/test.rs
  bszet-davinci/src/timetable/igd21.rs
  bszet-davinci/src/timetable/mod.rs
  bszet-davinci/templates/plan.stpl
  bszet-image/Cargo.toml
  bszet-image/src/lib.rs
  bszet-mind/Cargo.toml
  bszet-mind/src/main.rs
  bszet-mind/static/Inter-Bold.woff2
  bszet-mind/static/Inter-Regular.woff2
  bszet-mind/static/inter.css
  bszet-notify/Cargo.toml
  bszet-notify/src/telegram.rs
  bszet-notify/src/test.rs
Labels: enhancement, size/XXL

#12 Added sentry
  Cargo.lock
  bszet-davinci/Cargo.toml
  bszet-image/Cargo.toml
  bszet-mind/Cargo.toml
  bszet-mind/src/main.rs
  bszet-notify/Cargo.toml
Labels: size/M

#14 Fixed "Von ... verschoben" and "Auf ... verschoben"
  bszet-davinci/src/change.rs
  bszet-mind/src/main.rs
Labels: bug, size/L
